name: "Build and Push Agent Tools Image"

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Convert owner and repo name to lowercase"
        id: string_ops
        run: |
          OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          REPO=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
          echo "tags=ghcr.io/$OWNER/$REPO:latest" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.string_ops.outputs.tags }}
